ALTER TABLE ra_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE ra_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE ra_lead_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE applicant_cvs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ra_files ENABLE ROW LEVEL SECURITY;
